### ISSUE TITLE
Create GitHub workflows for automation

### ISSUE THREAD

**Issue by porfanid** [nasa/daidalus#13]
You should create github workflows to automate checking the changes that someone does to the code by comparing that to the desired output from the daidalus example.

**Comment by porfanid** [comment]
@aarondutle @cesaramh could you check this please?

**Comment by porfanid** [comment]
The solution I provided actually runs the code on the github and compares the results to the ones that were produced when I run the code manually on my machine.

This means that the output is hard-coded into each yml file as a variable.

**Comment by cesaramh** [comment]
Next release will include regression test scripts.
