### ISSUE TITLE
Issue with C++ DaidalusCore copy constructor

### ISSUE THREAD

**Issue by V-ALICE** [nasa/daidalus#2]
In the update to version 2.0.1 (from 2.0) some new logic was added to the `DaidalusCore::copyFrom` function:
```cpp
    if (urgency_strategy != NULL) {
      delete urgency_strategy;
    }
```
All of the other constructors set `urgency_strategy` so this works fine for assignment, but since `urgency_strategy` doesn't have a default value
```cpp
const UrgencyStrategy* urgency_strategy;
```
the majority of the time calling the copy constructor will throw an access violation

**Comment by cesaramh** [comment]
Thanks for reporting the issue. It's fixed in master and in DAIDALUSv2.0.1b
