### ISSUE TITLE
Error compiling C++ library on Windows

### ISSUE THREAD

**Issue by phuongtran7** [nasa/daidalus#22]
Hi,

I'm trying to compile the C++ library on Windows and encountered two errors when doing so. I've not tried using the library yet but after fixing the two errors, the compilation succeeded without any problem.

**Describe the Bug:**

1.  MSVC 19.38.33134.0 complains about missing semicolon at `const unsigned long lnan[2] = { 0xffffffff, 0x7fffffff }` ([https://github.com/nasa/daidalus/blob/master/C%2B%2B/include/Util.h#L36](https://github.com/nasa/daidalus/blob/master/C%2B%2B/include/Util.h#L36)) when compiling on Windows 10 with conformance mode turning on.

2. `M_PI_2` is undefined at `Velocity::angle()` ([https://github.com/nasa/daidalus/blob/master/C%2B%2B/src/Velocity.cpp#L133](https://github.com/nasa/daidalus/blob/master/C%2B%2B/src/Velocity.cpp#L133)).

**To Reproduce:**

1. Clone current development branch.
2. Create a simple CMake file to compile on Windows.
3. See error.

**Fix/Workaround:**

1.  Add semicolon at the end of `const unsigned long lnan[2] = { 0xffffffff, 0x7fffffff }`.
2. Looking at the Java code at [Velocity.java](https://github.com/nasa/daidalus/blob/master/Java/src/gov/nasa/larcfm/Util/Velocity.java#L347), it seems that the `return to_pi(M_PI_2-trk_);` should be `return to_pi((M_PI / 2.0) -trk_);`

**Additional Context:**

Here is the `CMakeLists.txt` file that I used, which based on [ModernCppStarter](https://github.com/TheLartians/ModernCppStarter):

```
cmake_minimum_required(VERSION 3.14...3.22)

project(
    Daidalus
    VERSION 1.0
    LANGUAGES CXX
)

# ---- Include guards ----
if(PROJECT_SOURCE_DIR STREQUAL PROJECT_BINARY_DIR)
    message(
        FATAL_ERROR
        "In-source builds not allowed. Please make a new directory (called a build directory) and run CMake from there."
    )
endif()

file(GLOB_RECURSE headers CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/include/*.h")
file(GLOB_RECURSE sources CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp")

add_library(${PROJECT_NAME} ${headers} ${sources})
set_target_properties(${PROJECT_NAME} PROPERTIES CXX_STANDARD 17)

target_compile_options(${PROJECT_NAME} PUBLIC "$<$<COMPILE_LANG_AND_ID:CXX,MSVC>:/permissive->")
target_compile_definitions(${PROJECT_NAME} PUBLIC "$<$<COMPILE_LANG_AND_ID:CXX,MSVC>:NOMINMAX>")
target_include_directories(${PROJECT_NAME} PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include/")
```

**Comment by cesaramh** [comment]
Thanks for the report. I fixed it in master and will push it to v2.0.4 soon.
