### ISSUE TITLE
Apparently no `setMinGroundSpeed`?

### ISSUE THREAD

**Issue by maxvonhippel** [nasa/daidalus#5]
Hi!  I noticed [the docs](https://nasa.github.io/daidalus/#bands-parameters) seem to imply the existence of a `setter` for `min_gs`, although the mentioned setter/getter is incorrect.

![baddoc](https://user-images.githubusercontent.com/4683443/140624751-b09d2116-0b42-4acc-928c-352b59a8c573.png)

[Searching the code](https://github.com/nasa/daidalus/search?q=setMinGroundSpeed), I don't see any setter named `setMinGroundSpeed`.  Does such a setter/getter pair exist?  If not, I think that (when there's time) the docs should be updated accordingly.

Thanks!

**Comment by aarondutle** [comment]
Thanks for the comment. There is a getter/setter for this parameter, but it's been changed to "HorizontalSpeed." Documentation is a work in progress...
