### ISSUE TITLE
`urgency_strategy_` is not freed in DaidalusCore destructor

### ISSUE THREAD

**Issue by reliable-matts** [nasa/daidalus#6]
Each non-copy `DaidalusCore` constructor allocates memory for `urgency_strategy_`. However, this memory is not freed in the `DaidalusCore` destructor. 

Suggestion for `C++/include/DaidalusCore.h`:

```cpp
virtual ~DaidalusCore() {
    delete urgency_strategy_;
}
```

**Comment by aarondutle** [comment]
Will be fixed in version 2.0.3. Thanks for the catch.
